version: "2"

services:
  db:
    build: opt/docker/db
    network_mode: host
  app:
    build: .
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASS: auth_pass